export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';

export const POST_TODOS = 'POST_TODOS';
export const POST_TODOS_SUCCESS = 'POST_TODOS_SUCCESS';
export const POST_TODOS_ERROR = 'POST_TODOS_ERROR';

export const DELETE_TODOS = 'DELETE_TODOS';
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS';
export const DELETE_TODOS_ERROR = 'DELETE_TODOS_ERROR';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';